version: '3.8'

services:
  app:
    build:
      args:
        - NODE_ENV=
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    command: yarn dev
    ports:
      - "3000:3000"
