version: '3.8'

services:
  app:
    build:
      args:
        - NODE_ENV=
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pages:/app/pages
      - ./source:/app/source
      - ./styles:/app/styles
    command: yarn dev
    ports:
      - "3000:3000"
